### ISSUE TITLE
Rename "install-spin" to "install"

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/spinnaker-orb#6]
Making a suggestion to rename "install-spin" to "install". This cuts down on the length of the command name and reduces duplicate information. 

https://github.com/CircleCI-Public/Orb-Policies/pull/4/commits/a89ff179c2733a69eb366b9c350a9e42298e1967#diff-a1fb6d0fc474c2f8666e073b8a71239cR22

**Comment by lokst** [comment]
@KyleTryon My concern is that `install` might be a little confusing as some may think it means that Spinnaker will be installed, and not just the spin CLI. Also as the Spinnaker project has a number of CLIs (`halyard`, `spin`) I think it'd be more flexible to retain `install-spin` so that we can add support for other CLIs if needed.

**Comment by lokst** [comment]
@KyleTryon Closing this as per our discussion
